name: Deploy to GitHub Pages

# Executar a action apenas quando há um push na branch principal
on:
  push:
    branches: ["main"] # Se a sua branch principal se chamar "master", mude para "master"

# Permissões necessárias para publicar no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas um deploy concorrente
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Opcional: Se usar pnpm em vez de npm, descomente as 3 linhas abaixo e apague a configuração do npm
      # - name: Install pnpm
      #   uses: pnpm/action-setup@v3
      #   with:
      #     version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' # Mude para 'pnpm' se estiver a utilizar pnpm
          
      - name: Install dependencies
        run: npm ci # Mude para 'pnpm install' se estiver a utilizar pnpm
        
      - name: Build project
        run: npm run build # Mude para 'pnpm run build' se estiver a utilizar pnpm
        env:
          # Estas variáveis são injetadas durante o processo de build
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # O Vite por predefinição gera os ficheiros finais na pasta 'dist'
          path: './dist'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4